import { Resend } from "resend";

let _resend: Resend | null = null;
function getResend(): Resend {
  if (!_resend) {
    _resend = new Resend(process.env.RESEND_API_KEY);
  }
  return _resend;
}

export async function sendDigestEmail({
  subject,
  markdown,
  period,
}: {
  subject: string;
  markdown: string;
  period: { start: string; end: string };
}) {
  const to = process.env.DIGEST_EMAIL;
  if (!to) {
    console.warn("Skipping digest email: DIGEST_EMAIL not configured");
    return { sent: false, reason: "no_recipient" };
  }

  const html = markdownToHtml(markdown, period);

  const { data, error } = await getResend().emails.send({
    from: process.env.RESEND_FROM_EMAIL ?? "SpendSense <onboarding@resend.dev>",
    to,
    subject,
    html,
  });

  if (error) {
    console.error("Failed to send digest email", error);
    return { sent: false, reason: error.message };
  }

  console.log("Digest email sent", { id: data?.id, to });
  return { sent: true, emailId: data?.id };
}

/** Convert markdown digest to styled HTML email */
function markdownToHtml(markdown: string, period: { start: string; end: string }): string {
  // Basic markdown → HTML conversion for email (no external deps needed)
  let html = markdown
    // Headers
    .replace(/^### (.+)$/gm, '<h3 style="color:#1a1a1a;font-size:16px;margin:16px 0 8px;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#1a1a1a;font-size:20px;margin:20px 0 10px;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="color:#1a1a1a;font-size:24px;margin:0 0 16px;">$1</h1>')
    // Bold and italic
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Unordered list items
    .replace(/^[-*] (.+)$/gm, '<li style="margin:4px 0;">$1</li>')
    // Numbered list items
    .replace(/^\d+\. (.+)$/gm, '<li style="margin:4px 0;">$1</li>')
    // Line breaks for remaining plain lines
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>");

  // Wrap consecutive <li> elements in <ul>
  html = html.replace(
    /(<li[^>]*>.*?<\/li>(?:<br>)?)+/g,
    (match) => `<ul style="padding-left:20px;margin:8px 0;">${match.replace(/<br>/g, "")}</ul>`
  );

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#333;line-height:1.6;">
  <div style="border-bottom:3px solid #10b981;padding-bottom:12px;margin-bottom:24px;">
    <h1 style="margin:0;font-size:24px;color:#1a1a1a;">💰 SpendSense</h1>
    <p style="margin:4px 0 0;color:#666;font-size:14px;">${period.start} → ${period.end}</p>
  </div>
  <div>
    <p>${html}</p>
  </div>
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e5e5;color:#999;font-size:12px;">
    Generated by SpendSense · Powered by Claude
  </div>
</body>
</html>`;
}
